$paths = @("D:\Projects\Lethal Company\LethalGargoyles\Plugin\bin\Debug\netstandard2.1\DropDaDeuce.LethalGargoyles.dll",
"C:\Users\mathe\.nuget\packages\harmonyx\2.7.0\lib\netstandard2.0\0Harmony.dll",
"D:\Program Files\Steam App\steamapps\common\Lethal Company\Lethal Company_Data\Managed\Assembly-CSharp.dll",
"C:\Users\mathe\.nuget\packages\bepinex.baselib\5.4.20\lib\netstandard2.0\BepInEx.dll",
"C:\Users\mathe\.nuget\packages\evaisa.lethallib\0.16.1\lib\netstandard2.1\LethalLib.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\Microsoft.Win32.Primitives.dll",
"C:\Users\mathe\.nuget\packages\mono.cecil\0.11.4\lib\netstandard2.0\Mono.Cecil.dll",
"C:\Users\mathe\.nuget\packages\mono.cecil\0.11.4\lib\netstandard2.0\Mono.Cecil.Mdb.dll",
"C:\Users\mathe\.nuget\packages\mono.cecil\0.11.4\lib\netstandard2.0\Mono.Cecil.Pdb.dll",
"C:\Users\mathe\.nuget\packages\mono.cecil\0.11.4\lib\netstandard2.0\Mono.Cecil.Rocks.dll",
"C:\Users\mathe\.nuget\packages\monomod.runtimedetour\21.12.13.1\lib\netstandard2.0\MonoMod.RuntimeDetour.dll",
"C:\Users\mathe\.nuget\packages\monomod.utils\21.12.13.1\lib\netstandard2.0\MonoMod.Utils.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\mscorlib.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\netstandard.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.AppContext.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Buffers.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Collections.Concurrent.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Collections.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Collections.NonGeneric.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Collections.Specialized.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.ComponentModel.Composition.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.ComponentModel.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.ComponentModel.EventBasedAsync.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.ComponentModel.Primitives.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.ComponentModel.TypeConverter.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Console.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Core.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Data.Common.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Data.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Diagnostics.Contracts.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Diagnostics.Debug.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Diagnostics.FileVersionInfo.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Diagnostics.Process.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Diagnostics.StackTrace.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Diagnostics.TextWriterTraceListener.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Diagnostics.Tools.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Diagnostics.TraceSource.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Diagnostics.Tracing.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Drawing.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Drawing.Primitives.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Dynamic.Runtime.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Globalization.Calendars.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Globalization.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Globalization.Extensions.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.IO.Compression.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.IO.Compression.FileSystem.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.IO.Compression.ZipFile.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.IO.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.IO.FileSystem.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.IO.FileSystem.DriveInfo.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.IO.FileSystem.Primitives.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.IO.FileSystem.Watcher.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.IO.IsolatedStorage.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.IO.MemoryMappedFiles.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.IO.Pipes.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.IO.UnmanagedMemoryStream.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Linq.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Linq.Expressions.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Linq.Parallel.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Linq.Queryable.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Memory.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Net.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Net.Http.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Net.NameResolution.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Net.NetworkInformation.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Net.Ping.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Net.Primitives.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Net.Requests.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Net.Security.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Net.Sockets.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Net.WebHeaderCollection.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Net.WebSockets.Client.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Net.WebSockets.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Numerics.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Numerics.Vectors.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.ObjectModel.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Reflection.DispatchProxy.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Reflection.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Reflection.Emit.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Reflection.Emit.ILGeneration.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Reflection.Emit.Lightweight.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Reflection.Extensions.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Reflection.Primitives.dll",
"C:\Users\mathe\.nuget\packages\system.reflection.typeextensions\4.7.0\ref\netstandard2.0\System.Reflection.TypeExtensions.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Resources.Reader.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Resources.ResourceManager.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Resources.Writer.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Runtime.CompilerServices.VisualC.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Runtime.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Runtime.Extensions.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Runtime.Handles.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Runtime.InteropServices.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Runtime.InteropServices.RuntimeInformation.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Runtime.Numerics.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Runtime.Serialization.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Runtime.Serialization.Formatters.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Runtime.Serialization.Json.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Runtime.Serialization.Primitives.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Runtime.Serialization.Xml.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Security.Claims.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Security.Cryptography.Algorithms.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Security.Cryptography.Csp.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Security.Cryptography.Encoding.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Security.Cryptography.Primitives.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Security.Cryptography.X509Certificates.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Security.Principal.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Security.SecureString.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.ServiceModel.Web.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Text.Encoding.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Text.Encoding.Extensions.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Text.RegularExpressions.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Threading.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Threading.Overlapped.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Threading.Tasks.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Threading.Tasks.Extensions.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Threading.Tasks.Parallel.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Threading.Thread.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Threading.ThreadPool.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Threading.Timer.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Transactions.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.ValueTuple.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Web.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Windows.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Xml.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Xml.Linq.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Xml.ReaderWriter.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Xml.Serialization.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Xml.XDocument.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Xml.XmlDocument.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Xml.XmlSerializer.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Xml.XPath.dll",
"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Xml.XPath.XDocument.dll",
"D:\Program Files\Steam App\steamapps\common\Lethal Company\Lethal Company_Data\Managed\Unity.Netcode.Runtime.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.AccessibilityModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.AIModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.AndroidJNIModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.AnimationModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.AssetBundleModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.AudioModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.ClothModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.ClusterInputModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.ClusterRendererModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.ContentLoadModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.CoreModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.CrashReportingModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.DirectorModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.DSPGraphModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.GameCenterModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.GIModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.GridModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.HotReloadModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.ImageConversionModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.IMGUIModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.InputLegacyModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.InputModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.JSONSerializeModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.LocalizationModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.ParticleSystemModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.PerformanceReportingModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.Physics2DModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.PhysicsModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.ProfilerModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.PropertiesModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.ScreenCaptureModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.SharedInternalsModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.SpriteMaskModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.SpriteShapeModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.StreamingModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.SubstanceModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.SubsystemsModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.TerrainModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.TerrainPhysicsModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.TextCoreFontEngineModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.TextCoreTextEngineModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.TextRenderingModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.TilemapModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.TLSModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.UIElementsModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.UIModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.UmbraModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.UnityAnalyticsCommonModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.UnityAnalyticsModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.UnityConnectModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.UnityCurlModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.UnityTestProtocolModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.UnityWebRequestAssetBundleModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.UnityWebRequestAudioModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.UnityWebRequestModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.UnityWebRequestTextureModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.UnityWebRequestWWWModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.VehiclesModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.VFXModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.VideoModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.VirtualTexturingModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.VRModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.WindModule.dll",
"C:\Users\mathe\.nuget\packages\unityengine.modules\2022.3.9\lib\netstandard2.0\UnityEngine.XRModule.dll")

$outputFile = "D:\Projects\Lethal Company\LethalGargoyles\file_existence_check.txt"
$errorLogFile = "D:\Projects\Lethal Company\LethalGargoyles\error_log.txt"

foreach ($path in $paths) {
    try {
        if (Test-Path -Path $path) {
            Write-Host "File exists: $path"
            Add-Content -Path $outputFile -Value "File exists: $path"
        } else {
            Write-Host "File does not exist: $path"
            Add-Content -Path $outputFile -Value "File does not exist: $path"
        }
    } catch {
        Add-Content -Path $errorLogFile -Value "Error processing path ${path}: $($_.Exception.Message)"
        Add-Content -Path $errorLogFile -Value "Error processing path $path: $($_.Exception.Message)"
    }
}

Start-Sleep -Seconds 5